-- AlterTable
ALTER TABLE "Partner" ADD COLUMN IF NOT EXISTS "userType" TEXT;
ALTER TABLE "Partner" ADD COLUMN IF NOT EXISTS "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Partner" ADD COLUMN IF NOT EXISTS "onboardingStep" INTEGER NOT NULL DEFAULT 0;
