import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/db';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ userId: string }> }
) {
  const session = await auth();
  if (!session?.user?.partnerId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  const partnerId = session.user.partnerId;

  const { userId } = await params;
  const { searchParams } = new URL(request.url);
  const appId = searchParams.get('appId');
  const campaignId = searchParams.get('campaignId');

  try {
    // Build base where clause scoped to partner's apps
    const baseWhere: any = {
      Campaign: {
        App: {
          partnerId,
          ...(appId ? { id: appId } : {}),
        },
      },
    };

    if (campaignId) {
      baseWhere.Campaign.id = campaignId;
    }

    // Referrals made by this user (as referrer) - code generation records only
    const referralsMadeWhere = {
      ...baseWhere,
      referrerId: userId,
      isConversionReferral: false, // Only count code generation records
    };

    // Clicks for codes generated by this user
    const clicksWhere = {
      Campaign: baseWhere.Campaign,
      referrerId: userId,
    };
    if (campaignId) {
      clicksWhere.campaignId = campaignId;
    }

    // Conversion referrals where this user is the referrer
    const conversionsWhere = {
      ...baseWhere,
      referrerId: userId,
      isConversionReferral: true,
      status: 'CONVERTED',
    };

    const [referralsMadeTotal, referralsMadeClicked, referralsMadeConverted, rewardsLegacyAgg] = await Promise.all([
      prisma.referral.count({ where: referralsMadeWhere }),
      prisma.click.count({ where: clicksWhere }),
      prisma.referral.count({ where: conversionsWhere }),
      prisma.referral.aggregate({
        where: conversionsWhere,
        _sum: { rewardAmount: true },
      }),
    ]);

    let pendingAmount = 0;
    let paidAmount = 0;
    try {
      const rewardWhere = {
        userId,
        App: {
          partnerId,
          ...(appId ? { id: appId } : {}),
        },
        ...(campaignId ? { Referral: { campaignId } } : {}),
      };
      const [rewardsPendingAgg, rewardsPaidAgg] = await Promise.all([
        prisma.reward.aggregate({
          where: { ...rewardWhere, status: { in: ['PENDING', 'APPROVED'] } },
          _sum: { amount: true },
        }),
        prisma.reward.aggregate({
          where: { ...rewardWhere, status: 'PAID' },
          _sum: { amount: true },
        }),
      ]);
      pendingAmount = rewardsPendingAgg._sum.amount ?? 0;
      paidAmount = rewardsPaidAgg._sum.amount ?? 0;
    } catch (_err) {
      paidAmount = rewardsLegacyAgg._sum.rewardAmount ?? 0;
      pendingAmount = 0;
    }

    // Referrals received by this user (as referee) - conversion referrals only
    const referralsReceivedWhere = {
      ...baseWhere,
      refereeId: userId,
      isConversionReferral: true, // Only conversion records
    };

    const referralsReceived = await prisma.referral.findMany({
      where: referralsReceivedWhere,
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
      take: 1,
    });

    // Referral codes generated by this user
    const referralCodesGenerated = await prisma.referral.findMany({
      where: referralsMadeWhere,
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    // Referral codes used by this user (conversion referrals where this user is the referee)
    const referralCodesUsed = await prisma.referral.findMany({
      where: {
        ...referralsReceivedWhere,
        isConversionReferral: true, // Only conversion records
      },
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    // Calculate clicks and conversions for each generated code
    const codesGeneratedWithStats = await Promise.all(
      referralCodesGenerated.map(async (ref) => {
        // Count clicks for this code
        const clicks = await prisma.click.count({
          where: {
            referralCode: ref.referralCode,
          },
        });

        // Count conversion referrals for this code
        const conversions = await prisma.referral.count({
          where: {
            originalReferralCode: ref.referralCode,
            isConversionReferral: true,
            status: 'CONVERTED',
          },
        });

        // Get list of who converted (refereeIds)
        const conversionRecords = await prisma.referral.findMany({
          where: {
            originalReferralCode: ref.referralCode,
            isConversionReferral: true,
            status: 'CONVERTED',
          },
          select: {
            refereeId: true,
            convertedAt: true,
            rewardAmount: true,
            isFlagged: true,
          },
          orderBy: { convertedAt: 'desc' },
        });

        // Sum total rewards from all conversions
        const totalRewardAmount = conversionRecords.reduce((sum, conv) => sum + (conv.rewardAmount || 0), 0);

        return {
          referralCode: ref.referralCode,
          campaignId: ref.campaignId,
          campaignName: ref.Campaign.name,
          appId: ref.Campaign.App.id,
          appName: ref.Campaign.App.name,
          status: ref.status,
          createdAt: ref.createdAt,
          clicks,
          conversions,
          totalRewardAmount,
          convertedUsers: conversionRecords.map(conv => ({
            refereeId: conv.refereeId,
            convertedAt: conv.convertedAt,
            rewardAmount: conv.rewardAmount || 0,
            isFlagged: conv.isFlagged,
          })),
        };
      })
    );

    const totalRewards = pendingAmount + paidAmount;

    return NextResponse.json({
      userId,
      referralsMade: {
        total: referralsMadeTotal,
        clicked: referralsMadeClicked,
        converted: referralsMadeConverted,
      },
      referralsReceived: referralsReceived.length > 0
        ? {
            total: referralsReceived.length,
            referrerId: referralsReceived[0].referrerId,
            referralCode: referralsReceived[0].referralCode,
            campaignId: referralsReceived[0].campaignId,
            campaignName: referralsReceived[0].Campaign.name,
            appId: referralsReceived[0].Campaign.App.id,
            appName: referralsReceived[0].Campaign.App.name,
            converted: referralsReceived[0].status === 'CONVERTED',
            receivedAt: referralsReceived[0].createdAt,
          }
        : null,
      rewardsEarned: {
        total: totalRewards,
        pending: pendingAmount,
        paid: paidAmount,
      },
      referralCodesGenerated: codesGeneratedWithStats,
      referralCodesUsed: referralCodesUsed.map((ref) => ({
        referralCode: ref.originalReferralCode || ref.referralCode, // Show original code
        conversionReferralCode: ref.referralCode, // Conversion record code
        referrerId: ref.referrerId,
        campaignId: ref.campaignId,
        campaignName: ref.Campaign.name,
        appId: ref.Campaign.App.id,
        appName: ref.Campaign.App.name,
        status: ref.status,
        usedAt: ref.createdAt,
        convertedAt: ref.convertedAt,
        rewardEarned: ref.rewardAmount || 0,
        isFlagged: ref.isFlagged,
      })),
    });
  } catch (error) {
    console.error('Error fetching user stats:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
