import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/db';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ userId: string }> }
) {
  const session = await auth();
  if (!session?.user?.partnerId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  const partnerId = session.user.partnerId;

  const { userId } = await params;
  const { searchParams } = new URL(request.url);
  const appId = searchParams.get('appId');
  const campaignId = searchParams.get('campaignId');

  try {
    // Build base where clause scoped to partner's apps
    const baseWhere: any = {
      Campaign: {
        App: {
          partnerId,
          ...(appId ? { id: appId } : {}),
        },
      },
    };

    if (campaignId) {
      baseWhere.Campaign.id = campaignId;
    }

    // Referrals made by this user (as referrer)
    const referralsMadeWhere = {
      ...baseWhere,
      referrerId: userId,
    };

    const rewardWhere = {
      userId,
      App: {
        partnerId,
        ...(appId ? { id: appId } : {}),
      },
      ...(campaignId ? { Referral: { campaignId } } : {}),
    };

    const [referralsMadeTotal, referralsMadeClicked, referralsMadeConverted, rewardsPendingAgg, rewardsPaidAgg] = await Promise.all([
      prisma.referral.count({ where: referralsMadeWhere }),
      prisma.referral.count({
        where: {
          ...referralsMadeWhere,
          status: { in: ['CLICKED', 'CONVERTED'] },
        },
      }),
      prisma.referral.count({
        where: {
          ...referralsMadeWhere,
          status: 'CONVERTED',
        },
      }),
      prisma.reward.aggregate({
        where: { ...rewardWhere, status: { in: ['PENDING', 'APPROVED'] } },
        _sum: { amount: true },
      }),
      prisma.reward.aggregate({
        where: { ...rewardWhere, status: 'PAID' },
        _sum: { amount: true },
      }),
    ]);

    // Referrals received by this user (as referee)
    const referralsReceivedWhere = {
      ...baseWhere,
      refereeId: userId,
    };

    const referralsReceived = await prisma.referral.findMany({
      where: referralsReceivedWhere,
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
      take: 1,
    });

    // Referral codes generated by this user
    const referralCodesGenerated = await prisma.referral.findMany({
      where: referralsMadeWhere,
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    // Referral codes used by this user
    const referralCodesUsed = await prisma.referral.findMany({
      where: referralsReceivedWhere,
      include: {
        Campaign: {
          include: {
            App: {
              select: {
                id: true,
                name: true,
              },
            },
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    // Calculate clicks and conversions for each generated code
    const codesGeneratedWithStats = await Promise.all(
      referralCodesGenerated.map(async (ref) => {
        const clicks = await prisma.referral.count({
          where: {
            referralCode: ref.referralCode,
            status: { in: ['CLICKED', 'CONVERTED'] },
          },
        });
        const conversions = await prisma.referral.count({
          where: {
            referralCode: ref.referralCode,
            status: 'CONVERTED',
          },
        });
        return {
          referralCode: ref.referralCode,
          campaignId: ref.campaignId,
          campaignName: ref.Campaign.name,
          appId: ref.Campaign.App.id,
          appName: ref.Campaign.App.name,
          status: ref.status,
          createdAt: ref.createdAt,
          clicks,
          conversions,
          rewardAmount: ref.rewardAmount || 0,
        };
      })
    );

    const pendingAmount = rewardsPendingAgg._sum.amount || 0;
    const paidAmount = rewardsPaidAgg._sum.amount || 0;
    const totalRewards = pendingAmount + paidAmount;

    return NextResponse.json({
      userId,
      referralsMade: {
        total: referralsMadeTotal,
        clicked: referralsMadeClicked,
        converted: referralsMadeConverted,
      },
      referralsReceived: referralsReceived.length > 0
        ? {
            total: referralsReceived.length,
            referrerId: referralsReceived[0].referrerId,
            referralCode: referralsReceived[0].referralCode,
            campaignId: referralsReceived[0].campaignId,
            campaignName: referralsReceived[0].Campaign.name,
            appId: referralsReceived[0].Campaign.App.id,
            appName: referralsReceived[0].Campaign.App.name,
            converted: referralsReceived[0].status === 'CONVERTED',
            receivedAt: referralsReceived[0].createdAt,
          }
        : null,
      rewardsEarned: {
        total: totalRewards,
        pending: pendingAmount,
        paid: paidAmount,
      },
      referralCodesGenerated: codesGeneratedWithStats,
      referralCodesUsed: referralCodesUsed.map((ref) => ({
        referralCode: ref.referralCode,
        referrerId: ref.referrerId,
        campaignId: ref.campaignId,
        campaignName: ref.Campaign.name,
        appId: ref.Campaign.App.id,
        appName: ref.Campaign.App.name,
        status: ref.status,
        usedAt: ref.createdAt,
        rewardEarned: ref.rewardAmount || 0,
      })),
    });
  } catch (error) {
    console.error('Error fetching user stats:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
